Upgrade libraries-bom version to latest
quarkiverse/quarkiverse-google-cloud-services pull request #66
Opened 2020-12-08 22:09 UTC by dzou

Try to upgrade the `libraries-bom` to the latest version.

@loicmathieu - I noticed our Spring Cloud GCP project was able to use the latest `libraries-bom` version with `micrometer-registry-stackdriver`; maybe the latest libraries-bom version resolves the issue that you encountered earlier.

Our output for `mvn dependency:tree` looked like this for us:

```
[ESC[1;34mINFOESC[m] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.4.0:compile
[ESC[1;34mINFOESC[m] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.4.0:compile
[ESC[1;34mINFOESC[m] |  \- io.micrometer:micrometer-core:jar:1.6.1:compile
[ESC[1;34mINFOESC[m] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[ESC[1;34mINFOESC[m] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime

// Micrometer deps here
[ESC[1;34mINFOESC[m] +- io.micrometer:micrometer-registry-stackdriver:jar:1.6.1:compile
[ESC[1;34mINFOESC[m] |  \- com.google.cloud:google-cloud-monitoring:jar:2.0.6:compile
[ESC[1;34mINFOESC[m] |     \- com.google.api.grpc:proto-google-cloud-monitoring-v3:jar:2.0.6:compile

[ESC[1;34mINFOESC[m] +- commons-io:commons-io:jar:2.5:test
[ESC[1;34mINFOESC[m] +- org.codehaus.janino:janino:jar:3.1.2:test
[ESC[1;34mINFOESC[m] |  \- org.codehaus.janino:commons-compiler:jar:3.1.2:test
```

Just wanted to give this a try and see if it passes the tests. For me the `main/` integration tests still seemed to work.

cc/ @meltsufin

2020-12-09 09:42 UTC, loicmathieu commented
@dzou the issue was on Quarkus side not on Google Cloud Services side!

One of the micrometer[ Quarkus  integration  tests](https://github.com/quarkusio/quarkus/tree/master/integration-tests) didn't work anymore when upgrading the BOM.

I can try to see if the issue is fixed in the latest GCP BOM but the challenge here is that the GCP BOM is defined inside the Quarkiverse Google Cloud Services libraries and can cause issue on extensions defined inside the Quarkus BOM.

I'll test on the Quarkus integration tests, I think the best would be to add the GCP BOM to the Quarkus BOM so this kind of issues can be detected, I'll need to open a discussion on Zulip for this.

2020-12-09 12:26 UTC, loicmathieu commented
Just ran some test on the Quarkus IT https://github.com/quarkusio/quarkus/tree/master/integration-tests/micrometer-native and it passes with the latest version of the library BOM, it previously fail with the library BOM version 10.0 but I cannot reproduce the issue even with the 1.10 BOM so a fix should have been done on micrometer or stackdriver side.

It should be safe to merge this one, it misse the update of guava that must be updated when updating the BOM as the BOM only contains the adroid version.

I still plan to propose to put the library BOM inside the Quarkus BOM to avoid dependency divergence from extensions inside Quarkus but this can be done later.

2020-12-09 12:27 UTC, loicmathieu requested changes
Can you update the Guava version in the meantime please ?

2020-12-09 18:43 UTC, dzou commented
> Can you update the Guava version in the meantime please ?

Done. I updated to `30.0-jre` based on the compatibility notes here: https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM#guava-versions--jre-or--android

2020-12-10 08:03 UTC, loicmathieu commented
Thanks

2020-12-10 08:03 UTC, loicmathieu approved these changes
LGTM

2020-12-10 08:03 UTC, merged